// (C) Generated by Claude
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { api, ApiError } from '@/lib/api'
import { FileUploadInput } from './FileUploadInput'
import { LoadingSpinner } from '@/components/shared/LoadingSpinner'
import { ErrorMessage } from '@/components/shared/ErrorMessage'

export function AnalyzeForm() {
  const router = useRouter()
  const [linkedInUrl, setLinkedInUrl] = useState('')
  const [rawText, setRawText] = useState('')
  const [cvFile, setCvFile] = useState<File | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!cvFile) {
      setError('Please select a CV file.')
      return
    }

    setIsLoading(true)
    setError(null)

    try {
      // Step 1: Upload CV
      const formData = new FormData()
      formData.append('file', cvFile)
      const cvResult = await api.cvs.upload(formData)

      // Step 2: Ingest profile
      const profileResult = await api.profiles.ingest({ linkedInUrl, rawText })

      // Step 3: Start analysis
      const analysisResult = await api.analyses.start({
        profileId: profileResult.id,
        cvId: cvResult.id,
      })

      // Step 4: Redirect to results
      router.push(`/results/${analysisResult.id}`)
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.detail)
      } else {
        setError('Something went wrong. Please try again.')
      }
      setIsLoading(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <label htmlFor="linkedInUrl" className="block text-sm font-medium text-slate-700 mb-1">
          LinkedIn Profile URL
        </label>
        <input
          id="linkedInUrl"
          type="url"
          value={linkedInUrl}
          onChange={(e) => setLinkedInUrl(e.target.value)}
          placeholder="https://www.linkedin.com/in/your-profile"
          required
          disabled={isLoading}
          className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent disabled:opacity-50"
        />
      </div>

      <div>
        <label htmlFor="rawText" className="block text-sm font-medium text-slate-700 mb-1">
          LinkedIn Profile Text
        </label>
        <p className="text-xs text-slate-500 mb-2">
          Go to your LinkedIn profile → click &ldquo;More&rdquo; → &ldquo;Save to PDF&rdquo; or copy the text directly from your profile page.
        </p>
        <textarea
          id="rawText"
          value={rawText}
          onChange={(e) => setRawText(e.target.value)}
          placeholder="Paste your full LinkedIn profile text here…"
          required
          rows={8}
          disabled={isLoading}
          className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent disabled:opacity-50 resize-none"
        />
      </div>

      <FileUploadInput onFileSelect={setCvFile} disabled={isLoading} />

      {error && <ErrorMessage message={error} />}

      <button
        type="submit"
        disabled={isLoading}
        className="w-full bg-primary text-white py-3 rounded-lg font-medium text-sm hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      >
        {isLoading ? (
          <span className="flex items-center justify-center gap-2">
            <span className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
            Analyzing…
          </span>
        ) : (
          'Analyze my profile'
        )}
      </button>
    </form>
  )
}
