// (C) Generated by Claude
'use client'

import { useRef, useState } from 'react'

const ALLOWED_TYPES = [
  'application/pdf',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
]

interface FileUploadInputProps {
  onFileSelect: (file: File | null) => void
  disabled?: boolean
}

export function FileUploadInput({ onFileSelect, disabled }: FileUploadInputProps) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [fileName, setFileName] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0] ?? null
    setError(null)

    if (!file) {
      setFileName(null)
      onFileSelect(null)
      return
    }

    if (!ALLOWED_TYPES.includes(file.type)) {
      setError('Only PDF and DOCX files are accepted.')
      setFileName(null)
      onFileSelect(null)
      if (inputRef.current) inputRef.current.value = ''
      return
    }

    setFileName(file.name)
    onFileSelect(file)
  }

  return (
    <div>
      <label className="block text-sm font-medium text-slate-700 mb-1">
        CV / Resume
      </label>
      <div
        className="relative flex items-center gap-3 px-3 py-2 border border-slate-300 rounded-lg cursor-pointer hover:border-primary transition-colors"
        onClick={() => !disabled && inputRef.current?.click()}
      >
        <input
          ref={inputRef}
          type="file"
          accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
          onChange={handleChange}
          disabled={disabled}
          className="sr-only"
        />
        <span className="text-xs font-medium text-primary border border-primary rounded px-2 py-1 shrink-0">
          Choose file
        </span>
        <span className="text-sm text-slate-500 truncate">
          {fileName ?? 'PDF or DOCX, max 10 MB'}
        </span>
      </div>
      {error && <p className="mt-1 text-xs text-red-600">{error}</p>}
    </div>
  )
}
