// (C) Generated by Claude
import Link from 'next/link'

export default function HomePage() {
  return (
    <main className="min-h-screen bg-white flex flex-col items-center justify-center px-4">
      <div className="max-w-2xl text-center">
        <h1 className="text-4xl font-bold text-slate-900 mb-4">
          LinkedIn Optimizer
        </h1>
        <p className="text-xl text-slate-600 mb-8">
          Get your LinkedIn profile fully rewritten by AI in under 60 seconds.
          Paste your profile, upload your CV, and walk away with copy-ready output.
        </p>
        <div className="flex gap-4 justify-center">
          <Link
            href="/signup"
            className="bg-primary text-white px-6 py-3 rounded-lg font-medium hover:bg-primary-600 transition-colors"
          >
            Get started free
          </Link>
          <Link
            href="/login"
            className="border border-slate-300 text-slate-700 px-6 py-3 rounded-lg font-medium hover:bg-slate-50 transition-colors"
          >
            Sign in
          </Link>
        </div>
      </div>
    </main>
  )
}
