// (C) Generated by Claude
import { AnalyzeForm } from '@/components/analyze/AnalyzeForm'

export default function AnalyzePage() {
  return (
    <main className="min-h-screen bg-slate-50 py-12 px-4">
      <div className="max-w-2xl mx-auto">
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-slate-900">Optimize your LinkedIn profile</h1>
          <p className="text-slate-500 mt-1">
            Paste your profile text, upload your CV, and get a full rewrite in under 60 seconds.
          </p>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-8">
          <AnalyzeForm />
        </div>
      </div>
    </main>
  )
}
