// (C) Generated by Claude
import { getAccessToken, clearAccessToken, setAccessToken } from './auth'

const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:5000'

export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly detail: string,
    public readonly errors?: Record<string, string[]>
  ) {
    super(detail)
    this.name = 'ApiError'
  }
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const token = getAccessToken()

  const headers: Record<string, string> = {
    ...(init.headers as Record<string, string>),
  }

  // Only set Content-Type for non-FormData requests
  if (!(init.body instanceof FormData)) {
    headers['Content-Type'] = 'application/json'
  }

  if (token) {
    headers['Authorization'] = `Bearer ${token}`
  }

  const res = await fetch(`${BASE_URL}${path}`, {
    ...init,
    headers,
    credentials: 'include',
  })

  if (res.status === 401) {
    // Attempt token refresh
    try {
      const refreshRes = await fetch(`${BASE_URL}/api/auth/refresh`, {
        method: 'POST',
        credentials: 'include',
      })

      if (refreshRes.ok) {
        const data = await refreshRes.json()
        setAccessToken(data.accessToken)

        // Retry original request with new token
        headers['Authorization'] = `Bearer ${data.accessToken}`
        const retryRes = await fetch(`${BASE_URL}${path}`, {
          ...init,
          headers,
          credentials: 'include',
        })

        if (retryRes.ok) {
          return retryRes.json() as Promise<T>
        }
      }
    } catch {
      // Refresh failed
    }

    clearAccessToken()
    if (typeof window !== 'undefined') {
      window.location.href = '/login'
    }
    throw new ApiError(401, 'Session expired. Please log in again.')
  }

  if (!res.ok) {
    const problem = await res.json().catch(() => ({ detail: 'An error occurred.' }))
    throw new ApiError(res.status, problem.detail ?? 'An error occurred.', problem.errors)
  }

  // Handle empty responses (204 No Content)
  const text = await res.text()
  return text ? (JSON.parse(text) as T) : ({} as T)
}

// ── Type definitions ──────────────────────────────────────────────────────────

export interface AuthResponse {
  accessToken: string
}

export interface CvResponse {
  id: string
  originalFilename: string
  uploadedAt: string
}

export interface ProfileResponse {
  id: string
  linkedInUrl: string
  ingestedAt: string
}

export interface ExperienceSection {
  title: string
  company: string
  bullets: string[]
}

export interface RewriteData {
  headlines: string[]
  about: string[]
  experience: ExperienceSection[]
  skills: string[]
  bannerSuggestion: string
  tips: string[]
}

export interface AnalysisResponse {
  id: string
  score: number
  problems: string[]
  status: 'scored' | 'generating' | 'complete' | 'failed'
  rewrite: RewriteData | null
}

export interface PaymentInitResponse {
  authorizationUrl: string
  reference: string
}

// ── API client ────────────────────────────────────────────────────────────────

export const api = {
  auth: {
    signup: (body: { email: string; password: string }) =>
      request<AuthResponse>('/api/auth/signup', {
        method: 'POST',
        body: JSON.stringify(body),
      }),
    login: (body: { email: string; password: string }) =>
      request<AuthResponse>('/api/auth/login', {
        method: 'POST',
        body: JSON.stringify(body),
      }),
    refresh: () =>
      request<AuthResponse>('/api/auth/refresh', { method: 'POST' }),
  },
  cvs: {
    upload: (formData: FormData) =>
      request<CvResponse>('/api/cvs', { method: 'POST', body: formData }),
  },
  profiles: {
    ingest: (body: { linkedInUrl: string; rawText: string }) =>
      request<ProfileResponse>('/api/profiles', {
        method: 'POST',
        body: JSON.stringify(body),
      }),
  },
  analyses: {
    start: (body: { profileId: string; cvId: string }) =>
      request<AnalysisResponse>('/api/analyses', {
        method: 'POST',
        body: JSON.stringify(body),
      }),
    get: (id: string) => request<AnalysisResponse>(`/api/analyses/${id}`),
  },
  payments: {
    initialize: () =>
      request<PaymentInitResponse>('/api/payments/initialize', {
        method: 'POST',
      }),
  },
}
