// (C) Generated by Claude
// JWT token store using sessionStorage for persistence across navigation

let _accessToken: string | null = null

export const setAccessToken = (token: string): void => {
  _accessToken = token
  if (typeof window !== 'undefined') {
    sessionStorage.setItem('accessToken', token)
  }
}

export const getAccessToken = (): string | null => {
  if (_accessToken) return _accessToken
  if (typeof window !== 'undefined') {
    const stored = sessionStorage.getItem('accessToken')
    if (stored) {
      _accessToken = stored
      return stored
    }
  }
  return null
}

export const clearAccessToken = (): void => {
  _accessToken = null
  if (typeof window !== 'undefined') {
    sessionStorage.removeItem('accessToken')
  }
}

export const isAuthenticated = (): boolean => getAccessToken() !== null
