// (C) Generated by Claude
// In-memory JWT token store — NOT localStorage (security best practice)

let _accessToken: string | null = null

export const setAccessToken = (token: string): void => {
  _accessToken = token
}

export const getAccessToken = (): string | null => _accessToken

export const clearAccessToken = (): void => {
  _accessToken = null
}

export const isAuthenticated = (): boolean => _accessToken !== null
