// (C) Generated by Claude
import { useMutation, useQuery } from '@tanstack/react-query'
import { api, type AnalysisResponse } from './api'

export const queryKeys = {
  analysis: (id: string) => ['analysis', id] as const,
}

export function useAnalysis(id: string) {
  return useQuery({
    queryKey: queryKeys.analysis(id),
    queryFn: () => api.analyses.get(id),
    refetchInterval: (query) => {
      const status = (query.state.data as AnalysisResponse | undefined)?.status
      if (status === 'complete' || status === 'failed') return false
      return 2000
    },
    staleTime: 0,
    enabled: !!id,
  })
}

export function useStartAnalysis() {
  return useMutation({
    mutationFn: api.analyses.start,
  })
}
